### ISSUE TITLE
Cannot find the *.jar executable files

### ISSUE THREAD

**Issue by yangchenyun** [ggodlewski/smux-anki-converter#2]
Hi, 
   Great discovery when I found this repository as I am trying to archive the same conversion. As I am not a Java programer, I want to know where to find the *.jar executable mentioned in the README?

Best,

**Comment by ggodlewski** [comment]
It's available at https://github.com/ggodlewski/smux-anki-converter/downloads :)

**Comment by yangchenyun** [comment]
Godlewski,
     Thanks for that:)

## 

杨晨昀 Steven Yang / Designer and Web Developer
blog.yangchenyun.com
